#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Atualiza a lista de pacotes
sudo apt-get -y update

# Atualiza os pacotes do sistema
sudo apt-get -y upgrade

# Instala o apache, php5 e bibliotéca apache | mysql cliente, servidor e mysqlnd para usar o mysqli |
# servidor FTP VSFTPD (Very Secury FTP Daemon)
sudo apt-get -y install apache2 php5 libapache2-mod-php5 mysql-client mysql-server mysqlnd vsftpd

# Reinicia o apache para efetivar as mudanças
sudo apachectl restart

# Instala o GIT
apt-get install git-core

# Clona o repositório WiringPI, entra na pasta, verifica se existe atualização e compila a biblioteca.
#git clone git://git.drogon.net/wiringPi
#cd wiringPi
#git pull origin
#./build